/* Gestão de Jardinagem — V2 funcional local-first */
const KEY="jardinagem-v1-data";
const defaultData={settings:{companyName:"",legalName:"",nif:"",address:"",postal:"",phone:"",email:"",logo:null,hourlyRate:25,fixedPrice:50,minPrice:50,weeklyCapacity:40,workStart:"08:00",workEnd:"18:00",materialMargin:10,backupIntervalDays:30,lastBackup:null,serviceTypes:["Corte de relva","Aparar sebes","Limpeza simples","Instalação de rega","Outro"]},clients:[],jobs:[],sessions:[],costs:[],payments:[],quotes:[],equipment:[],maintenance:[],photos:[]};
let data=load(),route="home",calDate=new Date(),calView="week",homeFilter={from:null,to:null};
function mergeDefaults(raw){const d=structuredClone(defaultData); if(!raw||typeof raw!=="object")return d; for(const k of Object.keys(d)) d[k]=raw[k]??d[k]; d.settings={...structuredClone(defaultData.settings),...(raw.settings||{})}; return d}
function load(){try{const d=mergeDefaults(JSON.parse(localStorage.getItem(KEY)||"{}"));let cmax=0,jmax=0,qmax=0;d.clients.forEach(c=>{const n=Number(String(c.number||"").replace(/\D/g,""));cmax=Math.max(cmax,n)});d.jobs.forEach(j=>{const n=Number(String(j.number||"").replace(/\D/g,""));jmax=Math.max(jmax,n)});d.quotes.forEach(q=>{const n=Number(String(q.number||"").replace(/\D/g,""));qmax=Math.max(qmax,n)});d.clients.forEach(c=>{if(!c.number)c.number=`C${String(++cmax).padStart(4,"0")}`});d.jobs.forEach(j=>{if(!j.number)j.number=`#${String(++jmax).padStart(4,"0")}`;if(!j.serviceTypes)j.serviceTypes=j.type&&j.type!=="Outro"?[j.type]:[];if(!j.segments)j.segments=[{start:j.start,end:j.end}];j.plannedStart=j.plannedStart||j.start;j.plannedEnd=j.plannedEnd||j.end});d.quotes.forEach(q=>{if(!q.number)q.number=`ORC${String(++qmax).padStart(4,"0")}`});return d}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function uid(p){return p+"_"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function nextNumber(arr,prefix){let max=0;arr.forEach(x=>{const n=Number(String(x.number||"").replace(/\D/g,""));if(n>max)max=n});return `${prefix}${String(max+1).padStart(4,"0")}`}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function localDateInput(d){const x=new Date(d||Date.now());const p=n=>String(n).padStart(2,"0");return `${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}T${p(x.getHours())}:${p(x.getMinutes())}`}
function localDayKey(d){const x=new Date(d);const p=n=>String(n).padStart(2,"0");return `${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}`}
function fmtDate(d){return new Intl.DateTimeFormat("pt-PT",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d))}
function fmtTime(d){return new Intl.DateTimeFormat("pt-PT",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(d))}
function hours(ms){return ms/3600000}
function money(v){return new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(Number(v)||0)}
function client(id){return data.clients.find(c=>c.id===id)}
function clientName(id){return client(id)?.name||"Cliente"}
function job(id){return data.jobs.find(j=>j.id===id)}
function jobSessions(id){return data.sessions.filter(s=>s.jobId===id)}
function workedHours(id){return jobSessions(id).reduce((a,s)=>a+(Number(s.duration)||0),0)}
function activeSession(){return data.sessions.find(s=>s.active)}
function paid(id){return data.payments.filter(p=>p.jobId===id).reduce((a,p)=>a+(Number(p.amount)||0),0)}
function laborCharge(j){if(!j)return 0; return j.priceType==="hourly" ? workedHours(j.id)*(Number(j.hourlyRate)||0) : Number(j.price)||0}
function actualCharge(j){if(!j)return 0; return laborCharge(j)+data.costs.filter(c=>c.jobId===j.id).reduce((a,c)=>a+materialClientValue(c),0)}
function jobCosts(id){return data.costs.filter(c=>c.jobId===id).reduce((a,c)=>a+(Number(c.amount)||0),0)}
function materialClientValue(cost){return Number(cost.amount||0)*(1+(Number(cost.margin??data.settings.materialMargin)||0)/100)}
function statusClass(s){return String(s||"").replaceAll(" ","-")}
function titleFor(){return {home:"Hoje",calendar:"Calendário",jobs:"Trabalhos",clients:"Clientes",more:"Mais"}[route]||"Jardinagem"}
function render(){document.querySelector("#page-title").textContent=titleFor();document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===route));({home:renderHome,calendar:renderCalendar,jobs:renderJobs,clients:renderClients,more:renderMore}[route]||renderHome)(document.querySelector("#main"));checkBackupReminder()}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2600)}
function modal(title,body,buttons=""){document.querySelector("#modal-root").innerHTML=`<div class="modal-backdrop"><section class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div>${body}${buttons?`<div class="actions" style="margin-top:14px">${buttons}</div>`:""}</section></div>`}
function closeModal(){document.querySelector("#modal-root").innerHTML=""}
function field(label,id,value="",cls="",type="text",extra=""){return `<div class="${cls}"><label>${label}</label><input id="${id}" type="${type}" value="${esc(value??"")}" ${extra}></div>`}
function val(id){return document.getElementById(id)?.value||""}
function selectField(label,id,options,value="",cls="",multiple=false){return `<div class="${cls}"><label>${label}</label><select id="${id}" ${multiple?"multiple":""}>${options.map(o=>`<option value="${esc(o.value)}" ${multiple?(Array.isArray(value)&&value.includes(o.value)?"selected":""):(String(value)===String(o.value)?"selected":"")}>${esc(o.label)}</option>`).join("")}</select></div>`}
function selectedValues(id){return [...(document.getElementById(id)?.selectedOptions||[])].map(o=>o.value)}
function clientOptions(selected="",searchId=""){return data.clients.map(c=>`<option value="${c.id}" ${c.id===selected?"selected":""}>${esc(c.number||"")} — ${esc(c.name)}</option>`).join("")}
function jobLabel(j){return `${j.number||""} — ${clientName(j.clientId)} — ${serviceNames(j).join(", ")||j.description||"Trabalho"}`}
function serviceNames(j){return j.serviceTypes||((j.type&&j.type!=="Outro")?[j.type]:[])}
function priceForJobInput(type,est){return type==="hourly"?(Number(est)||0)*(Number(data.settings.hourlyRate)||0):Number(data.settings.fixedPrice||data.settings.minPrice||0)}

function renderHome(m){
 const today=new Date(), from=homeFilter.from?new Date(homeFilter.from+"T00:00"):new Date(today.getFullYear(),today.getMonth(),today.getDate()-29), to=homeFilter.to?new Date(homeFilter.to+"T23:59:59"):today;
 const inRange=j=>new Date(j.start)>=from&&new Date(j.start)<=to&&j.status!=="Cancelado";
 const jobs=data.jobs.filter(inRange), worked=jobs.filter(j=>workedHours(j.id)>0||["Em curso","Em pausa","Concluído"].includes(j.status));
 const openValue=worked.reduce((a,j)=>a+Math.max(0,actualCharge(j)-paid(j.id)),0), planned=jobs.reduce((a,j)=>a+(Number(j.estimatedHours)||0),0), plannedValue=jobs.reduce((a,j)=>a+(Number(j.price)||0),0), workedHoursTotal=worked.reduce((a,j)=>a+workedHours(j.id),0), revenue=worked.reduce((a,j)=>a+actualCharge(j),0), costs=data.costs.filter(c=>{const d=new Date(c.date||Date.now());return d>=from&&d<=to}).reduce((a,c)=>a+(c.jobId?materialClientValue(c):Number(c.amount)||0),0), result=revenue-costs;
 const cap=data.settings.weeklyCapacity||40; const scheduled=jobs.reduce((a,j)=>a+(Number(j.estimatedHours)||0),0), free=Math.max(0,cap-scheduled);
 m.innerHTML=`<div class="filterbar card"><div><strong>Período do painel</strong><div class="muted small">Sem filtro: últimos 30 dias</div></div><div class="filter-fields"><input id="home-from" type="date" value="${esc(homeFilter.from||"")}" onchange="applyHomeFilter()"><span>até</span><input id="home-to" type="date" value="${esc(homeFilter.to||"")}" onchange="applyHomeFilter()"><button class="secondary" onclick="homeFilter={from:null,to:null};render()">Limpar</button></div></div>
 <div class="grid grid4 kpi-grid"><div class="card kpi"><div class="muted small">Trabalhado / a receber</div><div class="big">${money(openValue)}</div><div class="muted small">Receita real: ${money(revenue)}</div></div><div class="card kpi"><div class="muted small">Orçamentado / agendado</div><div class="big">${money(plannedValue)}</div><div class="muted small">${planned.toFixed(1)} h estimadas</div></div><div class="card kpi"><div class="muted small">Horas trabalhadas</div><div class="big">${workedHoursTotal.toFixed(1)} h</div><div class="muted small">${jobs.length} trabalhos no período</div></div><div class="card kpi"><div class="muted small">Resultado</div><div class="big">${money(result)}</div><div class="muted small">Custos imputados/gerais: ${money(costs)}</div></div></div>
 <div class="grid grid3"><div class="card"><div class="muted small">Capacidade semanal</div><div class="big">${free.toFixed(1)} h livres</div><div class="progress"><i style="width:${Math.min(100,scheduled/cap*100)}%"></i></div><div class="muted small">${scheduled.toFixed(1)} h agendadas / ${cap} h</div></div><div class="card"><div class="muted small">Pagamentos</div><div class="big">${money(worked.reduce((a,j)=>a+paid(j.id),0))}</div><div class="muted small">${jobs.filter(j=>paid(j.id)>=actualCharge(j)&&actualCharge(j)>0).length} pagos · ${jobs.filter(j=>paid(j.id)>0&&paid(j.id)<actualCharge(j)).length} parciais</div></div><div class="card"><div class="muted small">Eficiência</div><div class="big">${workedHoursTotal?money(revenue/workedHoursTotal)+"/h":"—"}</div><div class="muted small">Receita real por hora</div></div></div>
 <div class="section-title"><h2>Hoje</h2><button class="secondary" onclick="route='calendar';calView='day';calDate=new Date();render()">Ver dia</button></div><div class="stack">${data.jobs.filter(j=>localDayKey(j.start)===localDayKey(today)).sort((a,b)=>new Date(a.start)-new Date(b.start)).map(jobHTML).join("")||`<div class="card empty">Não há trabalhos agendados para hoje.</div>`}</div>`;
}
function applyHomeFilter(){homeFilter={from:val("home-from")||null,to:val("home-to")||null};render()}
function jobHTML(j){const wh=workedHours(j.id), charge=actualCharge(j), bal=Math.max(0,charge-paid(j.id));return `<div class="card job-card ${statusClass(j.status)}"><div class="row"><div><strong>${esc(j.number||"")} · ${esc(clientName(j.clientId))}</strong><div>${esc(serviceNames(j).join(", "))}</div>${j.description?`<div class="muted small">${esc(j.description)}</div>`:""}</div><span class="status s-${statusClass(j.status)}">${esc(j.status)}</span></div><div class="muted small" style="margin-top:7px">${fmtDate(j.start)} · ${fmtTime(j.start)}–${fmtTime(j.end)} · ${wh.toFixed(1)} h realizadas · ${money(charge)}${bal?` · ${money(bal)} por receber`:""}</div><div class="actions" style="margin-top:10px">${j.status==="Agendado"||j.status==="Em pausa"?`<button class="primary" onclick="startJob('${j.id}')">${j.status==="Em pausa"?"Retomar":"Iniciar"}</button>`:""}${j.status==="Em curso"?`<button class="secondary" onclick="pauseJob('${j.id}')">Pausar</button><button class="secondary" onclick="endSession('${j.id}')">Terminar sessão</button>`:""}${!['Concluído','Cancelado'].includes(j.status)?`<button class="secondary" onclick="jobDetail('${j.id}')">Detalhes</button>`:`<button class="secondary" onclick="jobDetail('${j.id}')">Detalhes</button>`}${j.status!=="Concluído"&&j.status!=="Cancelado"?`<button class="secondary" onclick="reschedule('${j.id}',${j.status==='Em pausa'})">Reagendar</button>`:""}${charge>paid(j.id)?`<button class="secondary" onclick="newPayment('${j.id}')">Pagamento</button>`:""}</div></div>`}

function renderJobs(m){m.innerHTML=`<div class="actions"><button class="primary" onclick="newJob()">+ Novo trabalho</button><button class="secondary" onclick="newQuote()">+ Orçamento</button></div><input class="search" id="job-search" placeholder="Pesquisar por cliente, nº ou serviço..." oninput="renderJobList()" style="margin-top:12px"><div id="job-list"></div>`;renderJobList()}
function renderJobList(){const q=(document.querySelector("#job-search")?.value||"").toLowerCase();const arr=data.jobs.filter(j=>`${clientName(j.clientId)} ${j.number} ${serviceNames(j).join(" ")} ${j.description||""}`.toLowerCase().includes(q)).sort((a,b)=>new Date(a.start)-new Date(b.start));document.querySelector("#job-list").innerHTML=arr.length?`<div class="stack">${arr.map(jobHTML).join("")}</div>`:`<div class="card empty">Ainda não existem trabalhos.</div>`}

function renderClients(m){m.innerHTML=`<div class="actions"><button class="primary" onclick="newClient()">+ Novo cliente</button></div><input class="search" id="client-search" placeholder="Pesquisar por nome ou nº de cliente..." oninput="renderClientList()" style="margin-top:12px"><div id="client-list"></div>`;renderClientList()}
function renderClientList(){const q=(document.querySelector("#client-search")?.value||"").toLowerCase();const arr=data.clients.filter(c=>`${c.name} ${c.number||""} ${c.company||""} ${c.phone||""}`.toLowerCase().includes(q));document.querySelector("#client-list").innerHTML=arr.length?`<div class="stack">${arr.map(c=>`<div class="card"><div class="row"><div><strong>${esc(c.number)}</strong><h3>${esc(c.name)}</h3><div class="muted">${esc(c.company||"")}</div></div><button class="secondary" onclick="clientDetail('${c.id}')">Abrir</button></div><div class="small muted">${esc(c.phone||"")} ${c.email?`· ${esc(c.email)}`:""}</div></div>`).join("")}</div>`:`<div class="card empty">Ainda não existem clientes.</div>`}
function newClient(c={}){modal(c.id?"Editar cliente":"Novo cliente",`<div class="form-grid">${c.id?`<div class="full info"><strong>N.º de cliente: ${esc(c.number)}</strong></div>`:""}${field("Nome *","c-name",c.name)}${field("Empresa","c-company",c.company)}${field("NIF","c-nif",c.nif)}${field("Telefone","c-phone",c.phone)}${field("Email","c-email",c.email)}${field("Código postal","c-postal",c.postal)}${field("Morada","c-address",c.address,"full")}${field("Localidade","c-local",c.local)}</div>`,`<button class="primary" onclick="saveClient(${c.id?`'${c.id}'`:"null"})">Guardar</button>${c.id?`<button class="danger" onclick="deleteClient('${c.id}')">Eliminar cliente</button>`:""}`)}
function saveClient(id){const name=val("c-name").trim();if(!name)return toast("Indica o nome do cliente.");const obj={id:id||uid("c"),number:id?(client(id)?.number):nextNumber(data.clients,"C"),name,company:val("c-company"),nif:val("c-nif"),phone:val("c-phone"),email:val("c-email"),postal:val("c-postal"),address:val("c-address"),local:val("c-local")};if(id){const i=data.clients.findIndex(c=>c.id===id);data.clients[i]=obj}else data.clients.push(obj);save();closeModal();render();toast(id?"Cliente atualizado.":`Cliente ${obj.number} criado.`)}
function deleteClient(id){const has=data.jobs.some(j=>j.clientId===id);if(!confirm("Pretende avançar com a eliminação?"))return;if(has)return toast("Não é possível eliminar um cliente com trabalhos associados. Pode editar os dados em vez disso.");data.clients=data.clients.filter(c=>c.id!==id);save();closeModal();render();toast("Cliente eliminado.")}
function clientDetail(id){const c=client(id),jobs=data.jobs.filter(j=>j.clientId===id);modal(`${c.number} · ${c.name}`,`<div class="grid grid2"><div><span class="muted small">Morada</span><br>${esc(c.address||"")} ${esc(c.postal||"")} ${esc(c.local||"")}</div><div><span class="muted small">Contacto</span><br>${esc(c.phone||"")} ${esc(c.email||"")}</div></div><div class="actions" style="margin-top:12px"><button class="secondary" onclick="newClient(client('${id}'));">Editar</button></div><h3 style="margin-top:18px">Histórico de trabalhos</h3><div class="stack">${jobs.length?jobs.map(jobHTML).join(""):`<div class="empty">Sem trabalhos.</div>`}</div>`)}

function calendarDateLabel(){if(calView==="day")return fmtDate(calDate);if(calView==="month")return new Intl.DateTimeFormat("pt-PT",{month:"long",year:"numeric"}).format(calDate);const mon=startOfWeek(calDate);return `${fmtDate(mon)} – ${fmtDate(addDays(mon,6))}`}
function startOfWeek(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function renderCalendar(m){m.innerHTML=`<div class="calendar-toolbar"><div class="calendar-head"><button onclick="shiftCal(-1)">‹</button><strong>${calendarDateLabel()}</strong><button onclick="shiftCal(1)">›</button></div><div class="seg"><button class="${calView==='day'?'active':''}" onclick="calView='day';renderCalendar(document.querySelector('#main'))">Dia</button><button class="${calView==='week'?'active':''}" onclick="calView='week';renderCalendar(document.querySelector('#main'))">Semana</button><button class="${calView==='month'?'active':''}" onclick="calView='month';renderCalendar(document.querySelector('#main'))">Mês</button></div></div>${calView==='month'?monthCalendar():hourCalendar()}<div class="legend"><span><i class="dot blue"></i>Agendado</span><span><i class="dot orange"></i>Em curso</span><span><i class="dot red"></i>Em pausa</span><span><i class="dot green"></i>Concluído</span></div><button class="primary" onclick="newJob()">+ Novo trabalho</button>`}
function shiftCal(n){calDate=calView==='day'?addDays(calDate,n):calView==='week'?addDays(calDate,n*7):new Date(calDate.getFullYear(),calDate.getMonth()+n,1);renderCalendar(document.querySelector("#main"))}
function hourCalendar(){const days=calView==='day'?[new Date(calDate)]:[0,1,2,3,4,5,6].map(i=>addDays(startOfWeek(calDate),i));const names=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"];const labels=[...Array(17)].map((_,i)=>`${String(i+6).padStart(2,"0")}:00`);return `<div class="week"><div class="time-col">${labels.map(x=>`<div class="time-label">${x}</div>`).join("")}</div>${days.map((d,i)=>dayColumn(d,i,names[i]||"")).join("")}</div>`}
function dayColumn(d,i,name){const key=localDayKey(d),dayJobs=data.jobs.filter(j=>localDayKey(j.start)===key);return `<div class="day"><div class="day-head">${name?name+" · ":""}${fmtDate(d)}</div><div class="time-grid"><div class="off-hours before" style="height:${Math.max(0,(parseHM(data.settings.workStart)-6)*60)}px"></div><div class="off-hours after" style="top:${Math.max(0,(parseHM(data.settings.workEnd)-6)*60)}px;height:${Math.max(0,(22-parseHM(data.settings.workEnd))*60)}px"></div>${dayJobs.map(j=>eventHTML(j,dayJobs)).join("")}</div></div>`}
function parseHM(v){const [h,m]=String(v||"00:00").split(":").map(Number);return h+(m||0)/60}
function eventHTML(j,arr){const st=new Date(j.start),en=new Date(j.end),top=Math.max(0,(st.getHours()+st.getMinutes()/60-6)*60),h=Math.max(28,(en-st)/3600000*60),overlaps=arr.filter(x=>new Date(x.start)<en&&new Date(x.end)>st),idx=overlaps.indexOf(j),width=100/Math.max(1,overlaps.length),left=idx*width;return `<div class="event ${statusClass(j.status)}" style="top:${top}px;height:${h}px;left:calc(${left}% + 3px);width:calc(${width}% - 6px)" onclick="jobDetail('${j.id}')"><strong>${esc(j.number)} · ${esc(clientName(j.clientId))}</strong><br>${esc(serviceNames(j).join(", "))}<br>${fmtTime(st)}–${fmtTime(en)}</div>`}
function monthCalendar(){const y=calDate.getFullYear(),mo=calDate.getMonth(),first=new Date(y,mo,1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));let cells="";for(let i=0;i<42;i++){const d=addDays(start,i),js=data.jobs.filter(j=>localDayKey(j.start)===localDayKey(d));cells+=`<div class="month-cell ${d.getMonth()!==mo?'other-month':''}"><div class="month-day">${d.getDate()}</div>${js.map(j=>`<button class="month-event ${statusClass(j.status)}" onclick="jobDetail('${j.id}')">${esc(j.number)} · ${esc(clientName(j.clientId))}<br>${fmtTime(j.start)} · ${esc(serviceNames(j).join(", "))}</button>`).join("")}</div>`}return `<div class="month-grid">${["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(x=>`<div class="month-weekday">${x}</div>`).join("")}${cells}</div>`}

function renderMore(m){m.innerHTML=`<div class="grid"><button class="card row" onclick="renderSection('quotes')"><span><strong>Orçamentos</strong><br><span class="muted">Criar, PDF e converter em trabalho</span></span><b>›</b></button><button class="card row" onclick="renderSection('finance')"><span><strong>Finanças</strong><br><span class="muted">Custos, pagamentos e rentabilidade</span></span><b>›</b></button><button class="card row" onclick="renderSection('equipment')"><span><strong>Equipamentos</strong><br><span class="muted">Garantias e manutenção</span></span><b>›</b></button><button class="card row" onclick="renderSection('settings')"><span><strong>Definições</strong><br><span class="muted">Empresa, serviços, preços, horário e backup</span></span><b>›</b></button></div>`}
function renderSection(s){const m=document.querySelector("#main");({quotes:renderQuotes,finance:renderFinance,equipment:renderEquipment,settings:renderSettings}[s]||renderMore)(m)}

function renderSettings(m){const s=data.settings;const serviceText=(s.serviceTypes||[]).join("\n");const logoBlock=s.logo?`<div class="logo-preview"><img src="${s.logo}" alt="Logo"><button class="danger" onclick="data.settings.logo=null;save();renderSection('settings')">Remover logo</button></div>`:"";m.innerHTML=`<div class="card"><h2>Empresa</h2><div class="form-grid">${field("Nome comercial","set-company",s.companyName)}${field("Nome legal","set-legal",s.legalName)}${field("NIF","set-nif",s.nif)}${field("Telefone","set-phone",s.phone)}${field("Email","set-email",s.email)}${field("Código postal","set-postal",s.postal)}${field("Morada","set-address",s.address,"full")}${field("Logo (PNG/JPG)","set-logo",s.logo?"Logo carregado":"","full","file","accept='.png,.jpg,.jpeg' onchange='previewLogo(this)'")}</div>${logoBlock}<button class="primary" onclick="saveSettings()">Guardar empresa</button></div><div class="card"><h2>Preços e capacidade</h2><div class="form-grid">${field("Preço/hora (€)","set-rate",s.hourlyRate,"","number","step='0.01' min='0'")}${field("Preço fixo predefinido (€)","set-fixed",s.fixedPrice,"","number","step='0.01' min='0'")}${field("Preço mínimo (€)","set-min",s.minPrice,"","number","step='0.01' min='0'")}${field("Capacidade semanal (h)","set-cap",s.weeklyCapacity,"","number","step='0.5' min='0'")}${field("Margem sobre materiais (%)","set-margin",s.materialMargin,"","number","step='0.1' min='0'")}${field("Início do horário","set-work-start",s.workStart,"","time")}${field("Fim do horário","set-work-end",s.workEnd,"","time")}</div><p class="muted small">O calendário mantém sempre a escala 06:00–22:00. Fora do horário definido, a área aparece a cinzento mais escuro, mas continuam permitidos trabalhos.</p><h3>Tipos de serviço</h3><textarea id="set-services" rows="6" placeholder="Um serviço por linha">${esc(serviceText)}</textarea><div class="actions" style="margin-top:10px"><button class="primary" onclick="saveSettings()">Guardar preços, horário e serviços</button></div></div><div class="card"><h2>Cópia de segurança</h2><p class="muted">Último backup: ${s.lastBackup?new Date(s.lastBackup).toLocaleString("pt-PT"):"Nunca"}</p>${field("Relembrar a cada (dias) — mínimo 30","set-backup",Math.max(30,Number(s.backupIntervalDays)||30),"","number","min='30' step='1'")}<div class="actions"><button class="primary" onclick="exportBackup()">Fazer backup</button><button class="secondary" onclick="importBackup()">Restaurar backup</button><button class="secondary" onclick="exportCSV()">Exportar CSV</button></div></div>`}
function previewLogo(input){const f=input.files?.[0];if(!f)return;if(!/image\/(png|jpeg)/.test(f.type))return toast("O logo deve ser PNG ou JPG.");const r=new FileReader();r.onload=()=>{data.settings.logo=r.result;renderSection("settings")};r.readAsDataURL(f)}
function saveSettings(){const s=data.settings;s.companyName=val("set-company");s.legalName=val("set-legal");s.nif=val("set-nif");s.phone=val("set-phone");s.email=val("set-email");s.postal=val("set-postal");s.address=val("set-address");s.hourlyRate=Number(val("set-rate"))||0;s.fixedPrice=Number(val("set-fixed"))||0;s.minPrice=Number(val("set-min"))||0;s.weeklyCapacity=Number(val("set-cap"))||0;s.materialMargin=Math.max(0,Number(val("set-margin"))||0);s.workStart=val("set-work-start")||"08:00";s.workEnd=val("set-work-end")||"18:00";s.serviceTypes=val("set-services").split("\n").map(x=>x.trim()).filter(Boolean);s.backupIntervalDays=Math.max(30,Number(val("set-backup"))||30);save();toast("Definições guardadas.")}

function newJob(prefill={}){if(!data.clients.length)return modal("Primeiro cliente","É necessário criar um cliente antes de criar um trabalho.",`<button class="primary" onclick="closeModal();newClient()">Criar cliente</button>`);const now=new Date();const start=prefill.start||localDateInput(now);const est=prefill.estimatedHours||2;const parts=prefill.parts||1;const opts=(data.settings.serviceTypes||[]).map(x=>({value:x,label:x}));modal("Novo trabalho",`<div class="form-grid"><div class="full"><label>Cliente *</label><select id="j-client">${clientOptions(prefill.clientId||data.clients[0].id)}</select></div>${selectField("Tipo de serviço *","j-services",opts,prefill.serviceTypes||[],"full",true)}${field("Descrição","j-desc",prefill.description||"")}${field("N.º de horas estimadas *","j-est",est,"","number","step='0.25' min='0.25' onchange='syncJobPrice()'")}${field("N.º de partes do trabalho *","j-parts",parts,"","number","step='1' min='1' onchange='renderJobParts()'")}${selectField("Periodicidade","j-frequency",[{value:"Pontual",label:"Pontual"},{value:"Semanal",label:"Semanal"},{value:"Quinzenal",label:"Quinzenal"},{value:"Mensal",label:"Mensal"},{value:"Anual",label:"Anual"}],prefill.frequency||"Pontual")}${field("N.º de ocorrências (se periódico)","j-occurrences",prefill.occurrences||12,"","number","min='1' step='1'")}</div><div id="job-parts"></div><div class="form-grid">${selectField("Preço","j-priceType",[{value:"hourly",label:"À hora"},{value:"fixed",label:"Preço fixo"}],prefill.priceType||"hourly")}${field("Valor acordado (€)","j-price",prefill.price??priceForJobInput(prefill.priceType||"hourly",est),"","number","step='0.01' min='0' onchange='validateMinPriceHint()'")}${field("Notas","j-notes",prefill.notes||"","full")}</div>`,`<button class="primary" onclick="saveJob()">Guardar</button>`);renderJobParts(prefill.partsData);syncJobPrice()}
function renderJobParts(existing=[]){const n=Math.max(1,Number(val("j-parts"))||1),now=new Date();let html=`<div class="card subcard"><h3>Partes / agendamentos</h3><p class="muted small">O total das horas agendadas deve corresponder às horas estimadas. Pode distribuir as partes por vários dias.</p><div class="stack">`;for(let i=0;i<n;i++){const ex=existing[i],st=ex?.start||localDateInput(i?new Date(now.getTime()+i*86400000):now),en=ex?.end||localDateInput(new Date(new Date(st).getTime()+Math.max(1,(Number(val("j-est"))||2)/n)*3600000));html+=`<div class="part"><strong>Parte ${i+1}</strong>${field("Início","part-start-${i}",st,"","datetime-local")}${field("Fim","part-end-${i}",en,"","datetime-local")}</div>`}html+=`</div></div>`;document.querySelector("#job-parts").innerHTML=html}
function syncJobPrice(){const t=val("j-priceType")||"hourly",e=Number(val("j-est"))||0;const p=priceForJobInput(t,e);const el=document.querySelector("#j-price");if(el&&!el.dataset.manual)el.value=p.toFixed(2);if(el)el.oninput=()=>el.dataset.manual="1"}
function validateMinPriceHint(){const p=Number(val("j-price"))||0;if(p<(data.settings.minPrice||0))toast(`Valor abaixo do mínimo configurado: ${money(data.settings.minPrice)}.`)}
function saveJob(){const est=Number(val("j-est"))||0,parts=Math.max(1,Number(val("j-parts"))||1),type=val("j-priceType")||"hourly",price=Number(val("j-price"))||0,services=selectedValues("j-services"),frequency=val("j-frequency")||"Pontual",occurrences=Math.max(1,Number(val("j-occurrences"))||1);if(!val("j-client")||!services.length)return toast("Seleciona o cliente e pelo menos um tipo de serviço.");if(!est)return toast("Indica as horas estimadas.");if(price<(data.settings.minPrice||0)&&!confirm(`O valor calculado é inferior ao preço mínimo (${money(data.settings.minPrice)}). Pretende continuar?`))return;const segments=[];let total=0;for(let i=0;i<parts;i++){const st=new Date(val(`part-start-${i}`)),en=new Date(val(`part-end-${i}`));if(!val(`part-start-${i}`)||!val(`part-end-${i}`)||isNaN(st)||isNaN(en)||en<=st)return toast(`Verifica a Parte ${i+1}.`);total+=hours(en-st);segments.push({start:st.toISOString(),end:en.toISOString()})}if(Math.abs(total-est)>0.01){const diff=total-est;const msg=diff>0?`As horas agendadas excedem as horas esperadas em ${Math.abs(diff).toFixed(2)} h.`:`Faltam ${Math.abs(diff).toFixed(2)} h nas horas agendadas face às horas esperadas.`;if(!confirm(`${msg}\nPretende gravar mesmo assim?`))return}const first=segments[0],base={clientId:val("j-client"),serviceTypes:services,description:val("j-desc"),status:"Agendado",estimatedHours:est,scheduledHours:total,priceType:type,hourlyRate:Number(data.settings.hourlyRate)||0,price,notes:val("j-notes"),reschedules:[],recurrence:frequency!=="Pontual"?{frequency,occurrences}:null};const makeJob=(shift,copyIndex)=>{const shifted=segments.map(seg=>({start:shiftDate(seg.start,frequency,shift),end:shiftDate(seg.end,frequency,shift)}));const j={...base,id:uid("j"),number:nextNumber(data.jobs,"#"),start:shifted[0].start,end:shifted[0].end,segments:shifted,createdAt:new Date().toISOString(),plannedStart:shifted[0].start,plannedEnd:shifted[0].end,recurrenceIndex:copyIndex};data.jobs.push(j);return j};const firstJob=makeJob(0,1);if(frequency!=="Pontual"&&occurrences>1){for(let i=1;i<occurrences;i++)makeJob(i,i+1)}save();closeModal();route="calendar";calDate=new Date(firstJob.start);render();toast(frequency!=="Pontual"?`${occurrences} trabalhos periódicos agendados.`:`Trabalho ${firstJob.number} agendado.`)}
function shiftDate(date,frequency,n){const d=new Date(date);if(frequency==="Semanal")d.setDate(d.getDate()+7*n);else if(frequency==="Quinzenal")d.setDate(d.getDate()+14*n);else if(frequency==="Mensal")d.setMonth(d.getMonth()+n);else if(frequency==="Anual")d.setFullYear(d.getFullYear()+n);return d.toISOString()}

function jobDetail(id){const j=job(id),wh=workedHours(id),charge=actualCharge(j),p=paid(id),cost=jobCosts(id),photos=data.photos.filter(x=>x.jobId===id);modal(`${j.number} · Detalhe do trabalho`,`<div class="card"><div class="row"><div><strong>${esc(clientName(j.clientId))}</strong><div>${esc(serviceNames(j).join(", "))}</div>${j.description?`<div class="muted">${esc(j.description)}</div>`:""}</div><span class="status s-${statusClass(j.status)}">${esc(j.status)}</span></div><p class="muted">${j.segments?.map((s,i)=>`Parte ${i+1}: ${fmtDate(s.start)} · ${fmtTime(s.start)}–${fmtTime(s.end)}`).join("<br>")||`${fmtDate(j.start)} · ${fmtTime(j.start)}–${fmtTime(j.end)}`}</p><div class="grid grid4"><div><div class="muted small">Estimado</div><strong>${j.estimatedHours} h</strong></div><div><div class="muted small">Realizado</div><strong>${wh.toFixed(2)} h</strong></div><div><div class="muted small">Valor acordado €/h</div><strong>${j.priceType==='hourly'?money(j.hourlyRate):"Preço fixo"}</strong></div><div><div class="muted small">Total</div><strong>${money(charge)}</strong></div></div></div>
 <div class="section-title"><h3>Valor, custos e pagamento</h3><button class="secondary" onclick="newCost('${id}')">+ Custo</button></div><p>Custos: <strong>${money(cost)}</strong> · Resultado: <strong>${money(charge-cost)}</strong><br>Pago: <strong>${money(p)}</strong> · Em falta: <strong>${money(Math.max(0,charge-p))}</strong></p><div class="actions"><button class="secondary" onclick="newPayment('${id}')">+ Adicionar pagamento</button><button class="secondary" onclick="workReportPDF('${id}')">Relatório PDF</button></div>
 <div class="section-title"><h3>Sessões</h3></div><div class="stack">${jobSessions(id).length?jobSessions(id).map(s=>`<div class="card row"><span>${fmtDate(s.start)} · ${fmtTime(s.start)}–${s.end?fmtTime(s.end):"ativa"}</span><strong>${(s.duration||hours(Date.now()-new Date(s.start))).toFixed(2)} h</strong></div>`).join(""):`<div class="empty">Sem sessões.</div>`}</div>
 <div class="section-title"><h3>Fotografias</h3><button class="secondary" onclick="addPhotos('${id}')">+ Fotos</button></div><div class="photo-grid">${photos.map(p=>`<img src="${p.data}" alt="">`).join("")}</div><div class="actions" style="margin-top:14px">${j.status==='Agendado'||j.status==='Em pausa'?`<button class="primary" onclick="closeModal();startJob('${id}')">${j.status==='Em pausa'?"Retomar":"Iniciar"}</button>`:""}${j.status==='Em curso'?`<button class="secondary" onclick="closeModal();pauseJob('${id}')">Pausar</button><button class="secondary" onclick="closeModal();endSession('${id}')">Terminar sessão</button>`:""}${!['Concluído','Cancelado'].includes(j.status)?`<button class="secondary" onclick="reschedule('${id}',${j.status==='Em pausa'})">Reagendar</button><button class="secondary" onclick="completeJob('${id}')">Concluir</button>`:""}</div>`)}
function startJob(id){const active=activeSession();if(active&&active.jobId!==id){if(!confirm("Existe outro trabalho em curso. Pretende terminar a sessão atual e iniciar este trabalho?"))return;endSession(active.jobId,false)}const j=job(id),now=new Date();if(!j.startedAt){j.plannedStart=j.plannedStart||j.start;j.plannedEnd=j.plannedEnd||j.end;const durationMs=Math.max(30*60000,(new Date(j.end)-new Date(j.start)));j.start=now.toISOString();j.end=new Date(now.getTime()+durationMs).toISOString();if(j.segments?.length){j.segments[0]={start:j.start,end:j.end}}j.startedAt=now.toISOString()}j.status="Em curso";data.sessions.push({id:uid("s"),jobId:id,start:now.toISOString(),end:null,duration:0,active:true});save();render();toast(`Trabalho ${j.number} iniciado.`)}
function pauseJob(id){const s=activeSession();if(s?.jobId===id)finishSession(s);const j=job(id);j.status="Em pausa";save();render();toast("Trabalho pausado.")}
function endSession(id,rerender=true){const s=activeSession();if(s?.jobId===id)finishSession(s);const j=job(id);if(j.status==='Em curso')j.status='Em pausa';save();if(rerender){render();toast("Sessão terminada.")}}
function finishSession(s){s.end=new Date().toISOString();s.duration=hours(new Date(s.end)-new Date(s.start));s.active=false}
function completeJob(id){const s=activeSession();if(s?.jobId===id)finishSession(s);const j=job(id);j.status="Concluído";j.completedAt=new Date().toISOString();save();closeModal();render();toast("Trabalho concluído.")}

function reschedule(id,continuation){const j=job(id),s=j.segments?.[0]||{start:j.start,end:j.end};modal(continuation?"Reagendar continuação":"Reagendar",`<div class="form-grid">${field("Nova data/hora","r-start",localDateInput(s.start),"","datetime-local")}${field("Nova duração (h)","r-dur",hours(new Date(s.end)-new Date(s.start)).toFixed(2),"","number","step='0.25' min='0.25'")}${selectField("Motivo *","r-reason",[{value:"Más condições climatéricas",label:"Más condições climatéricas"},{value:"Solicitado pelo cliente",label:"Solicitado pelo cliente"},{value:"Cliente ausente",label:"Cliente ausente"},{value:"Sobreposição de trabalhos",label:"Sobreposição de trabalhos"},{value:"Outro",label:"Outro"}],"")}${field("Descrição do motivo (opcional)","r-other","","full")}</div>`,`<button class="primary" onclick="saveReschedule('${id}',${continuation})">Guardar</button>`);document.querySelector("#r-reason").onchange=e=>document.querySelector("#r-other").parentElement.style.display=e.target.value==='Outro'?"block":"none";document.querySelector("#r-other").parentElement.style.display="none"}
function saveReschedule(id,continuation){const j=job(id),reason=val("r-reason");if(!reason)return toast("O motivo do reagendamento é obrigatório.");const ns=new Date(val("r-start")),dur=Number(val("r-dur"))||1,ne=new Date(ns.getTime()+dur*3600000),old={start:j.start,end:j.end};j.reschedules=j.reschedules||[];j.reschedules.push({date:new Date().toISOString(),from:old,to:{start:ns.toISOString(),end:ne.toISOString()},reason,description:val("r-other")});if(continuation){j.segments=j.segments||[];j.segments.push({start:ns.toISOString(),end:ne.toISOString()});}else{j.start=ns.toISOString();j.end=ne.toISOString();j.segments=[{start:j.start,end:j.end}]};save();closeModal();calDate=ns;route="calendar";render();toast("Trabalho reagendado.")}

function renderQuotes(m){m.innerHTML=`<div class="actions"><button class="primary" onclick="newQuote()">+ Novo orçamento</button></div><div class="stack" style="margin-top:12px">${data.quotes.length?data.quotes.map(q=>`<div class="card"><div class="row"><div><strong>${esc(q.number)}</strong><div>${esc(clientName(q.clientId))}</div><div>${esc(q.services?.join(", ")||"")}</div></div><span class="status">${esc(q.status||"Rascunho")}</span></div><div class="muted small">${fmtDate(q.date)} · ${money(q.total)}</div><div class="actions" style="margin-top:8px"><button class="secondary" onclick="quotePDF('${q.id}')">Gerar PDF</button>${q.status!=="Convertido"?`<button class="primary" onclick="convertQuote('${q.id}')">Converter em trabalho</button>`:""}</div></div>`).join(""):`<div class="card empty">Ainda não existem orçamentos.</div>`}</div>`}
function newQuote(){if(!data.clients.length)return modal("Primeiro cliente","Cria um cliente antes de criar um orçamento.",`<button class="primary" onclick="closeModal();newClient()">Criar cliente</button>`);const now=localDateInput(new Date());const opts=(data.settings.serviceTypes||[]).map(x=>({value:x,label:x}));modal("Novo orçamento",`<div class="form-grid"><div class="full"><label>Cliente *</label><input id="q-client-search" placeholder="Pesquisar cliente..." oninput="filterQuoteClients()"><select id="q-client">${clientOptions(data.clients[0].id)}</select></div>${selectField("Tipo de trabalho *","q-services",opts,[],"full",true)}${field("Data proposta","q-date",now,"","datetime-local")}${field("N.º de horas esperadas","q-hours","","","number","step='0.25'")}${selectField("Periodicidade","q-frequency",[{value:"Pontual",label:"Pontual"},{value:"Semanal",label:"Semanal"},{value:"Quinzenal",label:"Quinzenal"},{value:"Mensal",label:"Mensal"},{value:"Anual",label:"Anual"}],"Pontual")}${field("Validade (dias)","q-valid","30","","number")}${field("Total (€)","q-total","0","","number","step='0.01'")}${field("Período do acordo","q-period")}${field("Descrição","q-desc","","full")}</div><div class="section-title"><h3>Materiais adicionais</h3><button class="secondary" onclick="addQuoteMaterialRow()">+ Material</button></div><div id="quote-materials"></div>${field("Notas","q-notes","","full")}`,`<button class="primary" onclick="saveQuote()">Guardar orçamento</button>`)}
function filterQuoteClients(){const q=val("q-client-search").toLowerCase();document.querySelector("#q-client").innerHTML=data.clients.filter(c=>`${c.name} ${c.number}`.toLowerCase().includes(q)).map(c=>`<option value="${c.id}">${esc(c.number)} — ${esc(c.name)}</option>`).join("")}
function addQuoteMaterialRow(){const box=document.querySelector("#quote-materials"),i=box.children.length;box.insertAdjacentHTML("beforeend",`<div class="material-row"><div><label>Descrição</label><input class="qm-desc" type="text"></div><div><label>Custo (€)</label><input class="qm-cost" type="number" min="0" step="0.01" value="0"></div><button class="danger" onclick="this.parentElement.remove()">×</button></div>`)}
function saveQuote(){const services=selectedValues("q-services");if(!val("q-client")||!services.length)return toast("Seleciona cliente e pelo menos um tipo de trabalho.");const mats=[...document.querySelectorAll("#quote-materials .material-row")].map(r=>({description:r.querySelector(".qm-desc")?.value||"",cost:Number(r.querySelector(".qm-cost")?.value)||0})).filter(x=>x.description||x.cost);const q={id:uid("q"),number:nextNumber(data.quotes,"ORC"),clientId:val("q-client"),services,description:val("q-desc"),expectedHours:Number(val("q-hours"))||0,frequency:val("q-frequency"),valid:Number(val("q-valid"))||30,total:Number(val("q-total"))||0,period:val("q-period"),materials:mats,notes:val("q-notes"),date:val("q-date")||new Date().toISOString(),status:"Rascunho"};data.quotes.push(q);save();closeModal();renderSection("quotes");toast(`Orçamento ${q.number} criado.`)}
function convertQuote(id){const q=data.quotes.find(x=>x.id===id);if(!q)return;const now=new Date();const st=new Date(now.getFullYear(),now.getMonth(),now.getDate(),9,0);const en=new Date(st.getTime()+Math.max(1,q.expectedHours||1)*3600000);const j={id:uid("j"),number:nextNumber(data.jobs,"#"),clientId:q.clientId,serviceTypes:q.services||[],description:q.description||"",status:"Agendado",start:st.toISOString(),end:en.toISOString(),segments:[{start:st.toISOString(),end:en.toISOString()}],estimatedHours:q.expectedHours||1,scheduledHours:q.expectedHours||1,priceType:"fixed",hourlyRate:Number(data.settings.hourlyRate)||0,price:Number(q.total)||0,notes:q.notes||"",createdAt:new Date().toISOString(),reschedules:[],recurrence:q.frequency!=="Pontual"?{frequency:q.frequency,occurrences:1}:null};data.jobs.push(j);q.status="Convertido";q.convertedAt=new Date().toISOString();q.jobId=j.id;save();closeModal();route="calendar";calDate=st;render();toast(`Orçamento ${q.number} convertido no trabalho ${j.number}.`)}
function quotePDF(id){const q=data.quotes.find(x=>x.id===id),c=client(q.clientId);printWindow(buildQuoteHTML(q,c),"Orçamento")}

function renderFinance(m){const costs=data.costs.reduce((a,c)=>a+(Number(c.amount)||0),0),payments=data.payments.reduce((a,p)=>a+(Number(p.amount)||0),0),revenue=data.jobs.reduce((a,j)=>a+actualCharge(j),0);m.innerHTML=`<div class="grid grid3"><div class="card"><div class="muted small">Receita real</div><div class="big">${money(revenue)}</div></div><div class="card"><div class="muted small">Custos</div><div class="big">${money(costs)}</div></div><div class="card"><div class="muted small">Pagamentos recebidos</div><div class="big">${money(payments)}</div></div></div><div class="section-title"><h2>Custos</h2><button class="primary" onclick="newCost()">+ Novo custo</button></div><div class="stack">${data.costs.length?data.costs.map(c=>`<div class="card row"><span>${esc(c.category)} · ${esc(c.description||"")}<br><span class="muted small">${c.jobId?jobLabel(job(c.jobId)):c.clientId?`${c.clientId}`:"Geral"} · custo ${money(c.amount)} · cliente ${money(c.jobId?materialClientValue(c):c.amount)}</span></span><strong>${money(c.amount)}</strong></div>`).join(""):`<div class="card empty">Sem custos registados.</div>`}</div><div class="section-title"><h2>Pagamentos</h2><button class="primary" onclick="newPayment()">+ Pagamento</button></div><div class="stack">${data.payments.length?data.payments.map(p=>`<div class="card row"><span>${esc(jobLabel(job(p.jobId)))}<br><span class="muted small">${fmtDate(p.date)} · ${esc(p.method)}</span></span><strong>${money(p.amount)}</strong></div>`).join(""):`<div class="card empty">Sem pagamentos registados.</div>`}</div>`}
function newCost(jobId=null){const cats=["Manutenção","Reparação","Trabalhos","Consumíveis","Outros"];modal("Novo custo",`<div class="form-grid">${selectField("Categoria *","cost-cat",cats.map(x=>({value:x,label:x})),"Consumíveis")}${field("Custo (€) *","cost-amount","0","","number","step='0.01' min='0'")}${field("Descrição","cost-desc","","full")}</div><div class="card subcard"><label>Associar</label><select id="cost-assoc" onchange="renderCostAssociation()"><option value="general">Geral</option><option value="client">Cliente</option><option value="job" ${jobId?"selected":""}>Trabalho</option></select><div id="cost-association"></div></div>`,`<button class="primary" onclick="saveCost('${jobId||""}')">Guardar</button>`);renderCostAssociation(jobId)}
function renderCostAssociation(forceJob=null){const mode=document.querySelector("#cost-assoc")?.value;if(mode==='general'){document.querySelector("#cost-association").innerHTML=`<p class="muted small">Custo geral, sem imputação a cliente.</p>`}else if(mode==='client'){document.querySelector("#cost-association").innerHTML=`<input id="cost-client-search" placeholder="Pesquisar cliente por nome ou nº" oninput="filterCostClients()"><select id="cost-client" onchange="renderCostJobsForClient()">${clientOptions()}</select><div id="cost-client-job"></div>`}else{document.querySelector("#cost-association").innerHTML=`<select id="cost-job"><option value="">Selecionar trabalho</option>${data.jobs.map(j=>`<option value="${j.id}">${esc(jobLabel(j))}</option>`).join("")}</select>`;if(forceJob)document.querySelector("#cost-job").value=forceJob}}
function filterCostClients(){const q=val("cost-client-search").toLowerCase();document.querySelector("#cost-client").innerHTML=data.clients.filter(c=>`${c.name} ${c.number}`.toLowerCase().includes(q)).map(c=>`<option value="${c.id}">${esc(c.number)} — ${esc(c.name)}</option>`).join("");renderCostJobsForClient()}
function renderCostJobsForClient(){const id=val("cost-client"),jobs=data.jobs.filter(j=>j.clientId===id);document.querySelector("#cost-client-job").innerHTML=`<label>Trabalho (opcional)</label><select id="cost-client-job-select"><option value="">Sem trabalho específico</option>${jobs.map(j=>`<option value="${j.id}">${esc(j.number)} — ${esc(serviceNames(j).join(", "))}</option>`).join("")}</select>`}
function saveCost(fromJob=""){const mode=val("cost-assoc"),amount=Number(val("cost-amount"))||0;if(!amount)return toast("Indica o custo.");let jobId="",clientId="";if(mode==='job')jobId=val("cost-job");if(mode==='client'){clientId=val("cost-client");jobId=val("cost-client-job-select");}if(fromJob)jobId=fromJob;data.costs.push({id:uid("cst"),category:val("cost-cat"),amount,margin:data.settings.materialMargin,jobId,clientId,description:val("cost-desc"),date:new Date().toISOString()});save();closeModal();if(fromJob)jobDetail(fromJob);else renderSection("finance");toast("Custo registado.")}
function newPayment(jobId=null){const jobs=data.jobs.filter(j=>actualCharge(j)>paid(j.id));modal("Adicionar pagamento",`<div class="form-grid">${jobId?`<div class="full info"><strong>${esc(jobLabel(job(jobId)))}</strong></div>`:`<div class="full"><label>Trabalho *</label><select id="pay-job">${jobs.map(j=>`<option value="${j.id}">${esc(jobLabel(j))} · em falta ${money(actualCharge(j)-paid(j.id))}</option>`).join("")}</select></div>`}${field("Valor (€) *","pay-amount",jobId?Math.max(0,actualCharge(jobId)-paid(jobId)).toFixed(2):"","","number","step='0.01' min='0.01'")}${selectField("Forma de pagamento *","pay-method",[{value:"Numerário",label:"Numerário"},{value:"Transferência bancária",label:"Transferência bancária"},{value:"MB WAY",label:"MB WAY"},{value:"Cartão",label:"Cartão"},{value:"Outro",label:"Outro"}],"Transferência bancária")}${field("Data","pay-date",localDateInput(new Date()),"","datetime-local")}</div>`,`<button class="primary" onclick="savePayment('${jobId||""}')">Guardar pagamento</button>`)}
function savePayment(forceJob=""){const jid=forceJob||val("pay-job"),amount=Number(val("pay-amount"))||0;if(!jid||amount<=0)return toast("Indica trabalho e valor.");if(amount>Math.max(0,actualCharge(job(jid))-paid(jid))+0.01)return toast("O pagamento excede o valor em falta.");data.payments.push({id:uid("pay"),jobId:jid,amount,method:val("pay-method"),date:val("pay-date")||new Date().toISOString()});save();closeModal();if(forceJob)jobDetail(forceJob);else renderSection("finance");toast("Pagamento registado.")}

function renderEquipment(m){m.innerHTML=`<div class="actions"><button class="primary" onclick="newEquipment()">+ Equipamento</button></div><div class="stack" style="margin-top:12px">${data.equipment.length?data.equipment.map(e=>{const overdue=maintenanceDue(e);return `<div class="card"><div class="row"><div><strong>${esc(e.type)}</strong><div>${esc(e.brand||"")} ${esc(e.model||"")}</div></div><span class="status">${e.warrantyEnd&&new Date(e.warrantyEnd)<new Date()?"Garantia expirada":e.warrantyEnd&&new Date(e.warrantyEnd)<addDays(new Date(),30)?"Garantia termina em breve":"Garantia válida"}</span></div><div class="muted small">Manutenção: ${e.maintenanceHours?`cada ${e.maintenanceHours} h`:""}${e.maintenanceMonths?` / ${e.maintenanceMonths} meses`:""} ${overdue?" · ⚠ manutenção em falta/próxima":""}</div></div>`}).join(""):`<div class="card empty">Ainda não existem equipamentos.</div>`}</div>`}
function newEquipment(){modal("Novo equipamento",`<div class="form-grid">${field("Tipo *","e-type")}${field("Marca","e-brand")}${field("Modelo","e-model")}${field("N.º de série","e-serial")}${field("Data de aquisição","e-date","","","date")}${field("Fornecedor","e-supplier")}${field("Preço (€)","e-price","0","","number")}${field("Fim da garantia","e-warranty","","","date")}${field("Manutenção a cada (h)","e-mh","","","number")}${field("Manutenção a cada (meses)","e-mm","","","number")}${field("Notas","e-notes","","full")}</div>`,`<button class="primary" onclick="saveEquipment()">Guardar</button>`)}
function saveEquipment(){const type=val("e-type").trim();if(!type)return toast("Indica o tipo de equipamento.");data.equipment.push({id:uid("e"),type,brand:val("e-brand"),model:val("e-model"),serial:val("e-serial"),date:val("e-date"),supplier:val("e-supplier"),price:Number(val("e-price"))||0,warrantyEnd:val("e-warranty"),maintenanceHours:Number(val("e-mh"))||0,maintenanceMonths:Number(val("e-mm"))||0,notes:val("e-notes")});save();closeModal();renderSection("equipment");toast("Equipamento registado.")}
function maintenanceDue(e){const arr=data.maintenance.filter(m=>m.equipmentId===e.id).sort((a,b)=>new Date(b.date)-new Date(a.date));if(!arr.length)return false;const last=new Date(arr[0].date),now=new Date();if(e.maintenanceMonths&&(now-last)/86400000>=e.maintenanceMonths*30)return true;return false}

function addPhotos(jobId){document.querySelector("#photo-input").dataset.job=jobId;document.querySelector("#photo-input").click()}
document.querySelector("#photo-input").addEventListener("change",async e=>{const jid=e.target.dataset.job;for(const file of e.target.files){const dataUrl=await compressImage(file);data.photos.push({id:uid("p"),jobId:jid,data:dataUrl,type:"outro",date:new Date().toISOString()})}save();e.target.value="";toast("Fotografias adicionadas.");if(document.querySelector("#modal-root").innerHTML)jobDetail(jid)})
function compressImage(file){return new Promise(res=>{const im=new Image(),r=new FileReader();r.onload=()=>{im.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.72))};im.src=r.result};r.readAsDataURL(file)})}

function workReportPDF(id){const j=job(id),c=client(j.clientId),s=data.settings,photos=data.photos.filter(p=>p.jobId===id);modal("Relatório de trabalhos realizados",`<p class="muted small">Escolhe os campos que queres mostrar ao cliente. O documento não é uma fatura fiscal.</p><div class="check-grid">${['clientName','clientAddress','clientPhone','clientEmail','date','services','description','hours','hourlyRate','total','costs','payment','notes'].map((x,i)=>`<label class="check"><input type="checkbox" id="rf-${x}" ${['clientName','date','services','hours','total','payment'].includes(x)?'checked':''}> ${({clientName:'Nome do cliente',clientAddress:'Morada',clientPhone:'Telefone',clientEmail:'Email',date:'Data',services:'Trabalhos realizados',description:'Descrição',hours:'Horas realizadas',hourlyRate:'Valor acordado €/h',total:'Valor a cobrar',costs:'Custos associados',payment:'Estado do pagamento',notes:'Notas'}[x])}</label>`).join('')}</div><label class="check"><input type="checkbox" id="rf-photos"> Incluir fotografias</label>`,`<button class="primary" onclick="generateReport('${id}')">Gerar PDF</button>`)}
function generateReport(id){const j=job(id),c=client(j.clientId),s=data.settings,p=paid(id),ch=actualCharge(j),show=x=>document.querySelector(`#rf-${x}`)?.checked,photos=data.photos.filter(x=>x.jobId===id);let html=`<div class="doc-head">${s.logo?`<img src="${s.logo}" class="doc-logo">`:''}<h1>RELATÓRIO DE TRABALHOS REALIZADOS</h1><p>${esc(s.companyName||s.legalName||'')}<br>${esc(s.address||'')} ${esc(s.postal||'')}<br>${esc(s.phone||'')} ${esc(s.email||'')}</p></div>`;if(show('clientName'))html+=`<h2>Cliente</h2><p>${esc(c.name)}${show('clientAddress')?`<br>${esc(c.address||'')} ${esc(c.postal||'')} ${esc(c.local||'')}`:''}${show('clientPhone')?`<br>${esc(c.phone||'')}`:''}${show('clientEmail')?`<br>${esc(c.email||'')}`:''}</p>`;html+=`<h2>Trabalho ${esc(j.number)}</h2>`;if(show('date'))html+=`<p><b>Data:</b> ${fmtDate(j.completedAt||j.start)}</p>`;if(show('services'))html+=`<p><b>Trabalhos realizados:</b> ${esc(serviceNames(j).join(', '))}</p>`;if(show('description'))html+=`<p><b>Descrição:</b> ${esc(j.description||'')}</p>`;if(show('hours'))html+=`<p><b>Horas realizadas:</b> ${workedHours(id).toFixed(2)} h</p>`;if(show('hourlyRate'))html+=`<p><b>Valor acordado €/h:</b> ${j.priceType==='hourly'?money(j.hourlyRate):'Preço fixo'}</p>`;if(show('total'))html+=`<p><b>Valor a cobrar:</b> ${money(ch)}</p>`;if(show('costs'))html+=`<p><b>Custos associados:</b> ${money(jobCosts(id))}</p>`;if(show('payment'))html+=`<p><b>Pagamento:</b> ${p>=ch?'Pago':p>0?`Parcial — ${money(p)} recebidos`:`Por pagar — ${money(ch)}`}</p>`;if(show('notes'))html+=`<p><b>Notas:</b> ${esc(j.notes||'')}</p>`;if(document.querySelector('#rf-photos')?.checked&&photos.length)html+=`<h2>Fotografias</h2><div class="doc-photos">${photos.map(x=>`<img src="${x.data}">`).join('')}</div>`;printWindow(html,'Relatório de trabalhos realizados')}
function buildQuoteHTML(q,c){const s=data.settings;return `<div class="doc-head">${s.logo?`<img src="${s.logo}" class="doc-logo">`:''}<h1>ORÇAMENTO</h1><p><b>${esc(s.companyName||s.legalName||'')}</b><br>${esc(s.address||'')} ${esc(s.postal||'')}<br>${esc(s.phone||'')} ${esc(s.email||'')}</p></div><h2>Cliente</h2><p>${esc(c?.name||'')}<br>${esc(c?.address||'')} ${esc(c?.postal||'')} ${esc(c?.local||'')}</p><h2>Trabalho proposto</h2><p>${esc(q.services?.join(', ')||'')}</p><p>${esc(q.description||'')}</p>${q.expectedHours?`<p>Horas esperadas: ${q.expectedHours} h</p>`:''}<p>Periodicidade: ${esc(q.frequency||'Pontual')}</p>${q.materials?.length?`<h3>Materiais</h3><ul>${q.materials.map(x=>`<li>${esc(x.description)} — ${money(x.cost*(1+(data.settings.materialMargin||0)/100))}</li>`).join('')}</ul>`:''}<h2>Total: ${money(q.total)}</h2><p>Validade: ${q.valid} dias</p><p>${esc(q.notes||'')}</p>`}
function printWindow(content,title){const w=window.open('','_blank');if(!w)return toast('Permite janelas para gerar o documento.');w.document.write(`<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:36px;color:#18211c}h1{font-size:25px}h2{margin-top:26px;border-bottom:1px solid #ddd;padding-bottom:6px}.doc-logo{max-width:180px;max-height:90px;object-fit:contain}.doc-photos{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.doc-photos img{width:100%;max-height:360px;object-fit:cover}li{margin:7px 0}@media print{body{padding:0}}</style></head><body>${content}<script>window.print()<\/script></body></html>`);w.document.close()}

function exportBackup(){data.settings.lastBackup=new Date().toISOString();save();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});downloadBlob(blob,`backup_jardinagem_${localDayKey(new Date())}.json`);toast('Backup criado.')}
function importBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!incoming.clients||!incoming.jobs||!incoming.settings)throw Error();const bd=incoming.settings.lastBackup?new Date(incoming.settings.lastBackup).toLocaleString('pt-PT'):'data não indicada';if(confirm(`Backup válido (${bd}). Substituir os dados atuais pelo backup?`)){data=mergeDefaults(incoming);save();render();toast('Backup restaurado.')}}catch{toast('Ficheiro de backup inválido.')}};r.readAsText(f)};input.click()}
function exportCSV(){const rows=[['Nº Cliente','Cliente','Nº Trabalho','Serviços','Estado','Início','Horas estimadas','Horas realizadas','Preço','Custos','Valor a cobrar','Pago','Em falta']];data.jobs.forEach(j=>rows.push([client(j.clientId)?.number||'',clientName(j.clientId),j.number,serviceNames(j).join(', '),j.status,j.start,j.estimatedHours,workedHours(j.id),j.price,jobCosts(j.id),actualCharge(j),paid(j.id),Math.max(0,actualCharge(j)-paid(j.id))]));const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),'trabalhos_jardinagem.csv');toast('CSV exportado.')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function checkBackupReminder(){const d=data.settings.lastBackup?new Date(data.settings.lastBackup):null,interval=Math.max(30,Number(data.settings.backupIntervalDays)||30);if(!d||((Date.now()-d.getTime())/86400000)>=interval){if(!sessionStorage.getItem('backupReminderShown')){sessionStorage.setItem('backupReminderShown','1');setTimeout(()=>modal('Cópia de segurança','Está na altura de fazer uma cópia de segurança dos seus dados.',`<button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="closeModal();exportBackup()">Fazer backup</button>`),500)}}}
let timerInterval=setInterval(()=>{if(activeSession()){const main=document.querySelector('#main');if(main)render()}},60000);
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route;render()}));document.querySelector('#backup-reminder-btn').addEventListener('click',()=>renderSection('settings'));if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();
